// ============================================================
// 标签刮削插件 — QuickJS 入口（main.js）
// ============================================================

// ---- 内联 router SDK ----
function createRouter(){var routes=[];function add(m,p,h){var k=[];var r='^'+p.replace(/:([^/]+)/g,function(_,x){k.push(x);return'([^/]+)'})+'$';routes.push({method:m,regex:new RegExp(r),keys:k,handler:h})}return{get:function(p,h){add('GET',p,h)},post:function(p,h){add('POST',p,h)},put:function(p,h){add('PUT',p,h)},handle:async function(req){var p=(req.path||'').replace(/\/$/,'')||'/';var m=(req.method||'GET').toUpperCase();for(var i=0;i<routes.length;i++){var r=routes[i];if(r.method!==m)continue;var ma=p.match(r.regex);if(ma){var pa={};for(var j=0;j<r.keys.length;j++)pa[r.keys[j]]=ma[j+1];req.params=pa;var res=await r.handler(req);if(res&&typeof res.statusCode!=='undefined')return res}}return{statusCode:404,headers:{},body:'Not Found'}}}}
function jsonResponse(d,s){return{statusCode:s||200,headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}}

var router=createRouter();

// 首页由 Go 层直接服务（保留 query string）
router.get('/',function(_){return{statusCode:302,headers:{'Location':'static/'},body:''}});
router.get('/config',async function(_){var r=await songloft.storage.get('scraper_config');return jsonResponse(r?JSON.parse(r):getDefaultConfig())});
router.put('/config',async function(req){var u=JSON.parse(req.body||'{}');var r=await songloft.storage.get('scraper_config');var c=r?JSON.parse(r):getDefaultConfig();Object.keys(u).forEach(function(k){c[k]=u[k]});await songloft.storage.set('scraper_config',JSON.stringify(c));return jsonResponse({status:'ok',config:c})});
router.get('/fpcalc/status',async function(_){var a=false;try{a=await songloft.command.exists('fpcalc')}catch(e){}if(!a)try{var r=await songloft.command.exec('fpcalc',['-version'],{timeout:5000});a=r.exitCode===0}catch(e2){}return jsonResponse({available:a})});
router.post('/fpcalc/install',async function(_){try{var i=await installFpcalc();return jsonResponse(i,i.success?200:500)}catch(e){return jsonResponse({success:false,error:String(e)},500)}});

// 刮削
router.post('/scrape/preview/:id',async function(req){var id=parseInt(req.params.id,10);if(!id)return jsonResponse({error:'无效ID'},400);var r=await doScrape(id);if(!r)return jsonResponse({error:'无匹配结果',songId:id},404);return jsonResponse(r)});
router.post('/scrape/batch',async function(req){var body=JSON.parse(req.body||'{}');var ids=body.ids||[];var results=[],ok=0,sk=0,fa=0;for(var i=0;i<ids.length;i++){try{var r=await doScrape(ids[i]);if(!r){sk++;continue}await sleep(500);var ws=await writeTags(ids[i],r);r.fileWriteStatus=ws;results.push(r);if(ws==='written'||ws==='skipped')ok++;else fa++}catch(e){songloft.log.warn('[scraper] 失败:'+e);fa++}}return jsonResponse({results:results,success:ok,skipped:sk,failed:fa})});
router.post('/scrape/:id',async function(req){var id=parseInt(req.params.id,10);if(!id)return jsonResponse({error:'无效ID'},400);var r=await doScrape(id);if(!r)return jsonResponse({error:'无匹配结果',songId:id},404);var ws=await writeTags(id,r);r.fileWriteStatus=ws;return jsonResponse(r)});

// 手动刮削（用户输入关键词）
router.post('/scrape/manual/:id',async function(req){var id=parseInt(req.params.id,10);if(!id)return jsonResponse({error:'无效ID'},400);var body=JSON.parse(req.body||'{}');var kw=body.keyword||'';var artist=body.artist||'';var title=body.title||'';if(!kw&&artist&&title)kw=artist+' '+title;if(!kw)return jsonResponse({error:'缺少关键词'},400);var cfg=await loadConfig();var sourceRank=[],allR=[],scores={};if(cfg.enable_netease&&cfg.netease_api_url){var nr=await fetchNetease(kw,cfg.netease_api_url);nr.forEach(function(r){r.score=scoreMatch({artist:artist,title:title},r)});if(nr.length){var b=nr.reduce(function(a,b){return a.score>b.score?a:b});scores['netease']=b.score;allR=allR.concat(nr);sourceRank.push('netease')}}if(cfg.enable_qqmusic&&cfg.qqmusic_api_url){var qr=await fetchQQ(kw,cfg.qqmusic_api_url);qr.forEach(function(r){r.score=scoreMatch({artist:artist,title:title},r)});if(qr.length){var b=qr.reduce(function(a,b){return a.score>b.score?a:b});scores['qqmusic']=b.score;allR=allR.concat(qr);sourceRank.push('qqmusic')}}if(cfg.enable_kugou&&cfg.kugou_api_url){var kr=await fetchKG(kw,cfg.kugou_api_url);kr.forEach(function(r){r.score=scoreMatch({artist:artist,title:title},r)});if(kr.length){var b=kr.reduce(function(a,b){return a.score>b.score?a:b});scores['kugou']=b.score;allR=allR.concat(kr);sourceRank.push('kugou')}}var best=null,bs=-1;allR.forEach(function(r){if(r.score>bs){bs=r.score;best=r}});if(!best)return jsonResponse({error:'无匹配',songId:id},404);return jsonResponse({songId:id,artist:best.artist,title:best.title,album:best.album||'',cover_url:best.cover_url||'',source:best.source,score:best.score,sourceScores:scores})});

// 歌曲列表
router.get('/songs',async function(req){var q=(req.query||'').match(/q=([^&]*)/);var kw=q?decodeURIComponent(q[1]):'';var songs=kw?await songloft.songs.search(kw):await songloft.songs.list({limit:10000,offset:0});return jsonResponse({songs:songs,total:songs.length})});

// === 配置 ===
function getDefaultConfig(){return{enable_acoustid:true,acoustid_api_key:'zxhegT36TAA',enable_netease:false,netease_api_url:'',enable_qqmusic:false,qqmusic_api_url:'',enable_kugou:false,kugou_api_url:''}}
async function loadConfig(){try{var r=await songloft.storage.get('scraper_config');return r?JSON.parse(r):getDefaultConfig()}catch(e){return getDefaultConfig()}}

// === 刮削引擎 ===
async function doScrape(songId){var song=await songloft.songs.getById(songId);if(!song)return null;var cand={artist:song.artist||'',title:song.title||''};var fp=song.file_path||'';if(!cand.artist&&fp){var fn=fp.replace(/^.*[/\]/,'').replace(/\.[^.]+$/,'');var m=fn.match(/^(.+?)\s*-\s*(.+?)(?:\s*\(.*?\))?\s*$/);if(m){cand.artist=m[1].trim();cand.title=m[2].trim()}else cand.title=fn}if(!cand.title)return null;var kw=(cand.artist+' '+cand.title).trim();songloft.log.info('[scraper] 刮削:'+kw);var cfg=await loadConfig();var allR=[],scores={};if(cfg.enable_acoustid&&fp){var fa=false;try{fa=await songloft.command.exists('fpcalc')}catch(e){}if(!fa)try{var tr=await songloft.command.exec('fpcalc',['-version'],{timeout:5000});fa=tr.exitCode===0}catch(e){}songloft.log.info('[scraper] 声纹:fpcalc='+fa);if(fa){try{songloft.log.info('[scraper] 声纹:提取指纹 '+fp);var fpd=await extractFp(fp);if(fpd){songloft.log.info('[scraper] 声纹:查询AcoustID dur='+Math.round(fpd.duration)+'s key='+(cfg.acoustid_api_key||'default'));var ar=await searchAcoustid(fpd,cfg.acoustid_api_key||'zxhegT36TAA');songloft.log.info('[scraper] 声纹:返回'+ar.length+'条');ar.forEach(function(r){r.score=scoreMatch(cand,r)});allR=allR.concat(ar);if(ar.length){var ba=ar.reduce(function(a,b){return a.score>b.score?a:b});scores['acoustid']=ba.score;songloft.log.info('[scraper] 声纹最佳:'+ba.artist+' - '+ba.title+' ='+ba.score.toFixed(2));if(ba.score>0.8){songloft.log.info('[scraper] 声纹命中!');ba.artist=toSimplified(ba.artist);ba.title=toSimplified(ba.title);ba.album=toSimplified(ba.album);var enr=await enrichCover(ba.artist,ba.title,cand,cfg);if(enr.cover_url){ba.cover_url=enr.cover_url;songloft.log.info('[scraper] 封面来自 '+enr.source)}var ly=await fetchLyrics(ba,cand,kw);if(!ly&&enr.lyrics)ly=enr.lyrics;return buildR(songId,ba,cand,scores,ly)}}}else{songloft.log.info('[scraper] 声纹:指纹提取失败')}}catch(e){songloft.log.info('[scraper] 声纹:异常 '+e)}}}if(cfg.enable_netease&&cfg.netease_api_url){var nr=await fetchNetease(kw,cfg.netease_api_url);nr.forEach(function(r){r.score=scoreMatch(cand,r)});if(nr.length){var bn=nr.reduce(function(a,b){return a.score>b.score?a:b});scores['netease']=bn.score;allR=allR.concat(nr)}await sleep(500)}if(cfg.enable_qqmusic&&cfg.qqmusic_api_url){var qr=await fetchQQ(kw,cfg.qqmusic_api_url);qr.forEach(function(r){r.score=scoreMatch(cand,r)});if(qr.length){var bq=qr.reduce(function(a,b){return a.score>b.score?a:b});scores['qqmusic']=bq.score;allR=allR.concat(qr)}await sleep(500)}if(cfg.enable_kugou&&cfg.kugou_api_url){var kr=await fetchKG(kw,cfg.kugou_api_url);kr.forEach(function(r){r.score=scoreMatch(cand,r)});if(kr.length){var bk=kr.reduce(function(a,b){return a.score>b.score?a:b});scores['kugou']=bk.score;allR=allR.concat(kr)}}
var parts=[];Object.keys(scores).forEach(function(k){parts.push(k+'='+scores[k].toFixed(2))});songloft.log.info('[scraper] 得分:'+(parts.join(', ')||'无'));var best=null,bs=-1;allR.forEach(function(r){if(r.score>bs){bs=r.score;best=r}});if(!best||bs<0.8){songloft.log.info('[scraper] 不足:'+(bs||0).toFixed(2));return null}if(!best.lyrics){try{var ly=await fetchLyrics(best,cand,kw);best.lyrics=ly||''}catch(e){}}return buildR(songId,best,cand,scores,best.lyrics)}
function buildR(id,b,c,s,ly){return{songId:id,artist:b.artist||c.artist,title:b.title||c.title,album:b.album||'',lyrics:ly||'',cover_url:b.cover_url||'',source:b.source,score:b.score,sourceScores:s}}

// === fpcalc ===
async function extractFp(fp){try{var r=await songloft.command.exec('fpcalc',['-json','/app/'+fp],{timeout:15000});if(r.exitCode!==0)return null;var d=JSON.parse(r.stdout);return d.fingerprint?{fingerprint:d.fingerprint,duration:d.duration||0}:null}catch(e){return null}}

// === AcoustID ===
async function searchAcoustid(fp,key){try{var u='https://api.acoustid.org/v2/lookup?client='+encodeURIComponent(key||'zxhegT36TAA')+'&duration='+Math.round(fp.duration)+'&fingerprint='+encodeURIComponent(fp.fingerprint)+'&meta=recordingids';var r=await fetch(u,{headers:{'User-Agent':'songloft-plugin-tag/1.0'}});if(!r.ok)return[];var d=await r.json();if(d.status!=='ok')return[];var res=[];for(var i=0;i<Math.min(d.results.length,3);i++){var rd=d.results[i];if(!rd.recordings||!rd.recordings.length)continue;var mb=await fetchMB(rd.recordings[0].id);if(mb)res.push({artist:mb.artist,title:mb.title,album:mb.album,score:rd.score||0,source:'acoustid'})}return res}catch(e){return[]}}
async function fetchMB(id){try{var r=await fetch('https://musicbrainz.org/ws/2/recording/'+id+'?inc=artists+releases&fmt=json',{headers:{'User-Agent':'songloft-plugin-tag/1.0'}});if(!r.ok)return null;var d=await r.json();var ar=(d['artist-credit']&&d['artist-credit'][0])?(d['artist-credit'][0].artist?d['artist-credit'][0].artist.name:d['artist-credit'][0].name):'';var ti=d.title||'';var al='';var rl=d.releases||[];for(var i=0;i<rl.length;i++){if(rl[i].status==='Official'){al=rl[i].title||'';break}}if(!al&&rl.length)al=rl[0].title||'';return(ar&&ti)?{artist:ar,title:ti,album:al}:null}catch(e){return null}}

// === 歌词下载 (从 netease) ===
async function fetchLyrics(r,cand,kw){try{var u='https://music.163.com/api/search/get?type=1&s='+encodeURIComponent((r.artist||cand.artist)+' '+(r.title||cand.title))+'&limit=1';var resp=await fetch(u,{headers:{'Referer':'https://music.163.com','User-Agent':'Mozilla/5.0'}});if(!resp.ok)return'';var d=await resp.json();var sid=d.result&&d.result.songs&&d.result.songs[0]?d.result.songs[0].id:0;if(!sid)return'';var lr=await fetch('https://music.163.com/api/song/lyric?id='+sid+'&lv=1',{headers:{'Referer':'https://music.163.com','User-Agent':'Mozilla/5.0'}});if(!lr.ok)return'';var ld=await lr.json();songloft.log.info('[scraper] 歌词:'+(ld.lrc?'ok':'无'));return ld.lrc?ld.lrc.lyric:''}catch(e){return''}}

// === 繁→简 ===
function toSimplified(s){if(!s)return s;var r='';var p='萬万與与醜丑專業丛東东絲丝丟丢兩两嚴严喪丧個个豐丰臨临為为麗丽舉举麼么義义烏乌樂乐喬乔習习鄉乡書书買买亂乱爭争於于虧亏雲云亙亘亞亚產产畝亩親亲褻亵嚲亸億亿僅仅從从侖仑倉仓儀仪們们價价眾众優优夥伙會会傴伛傘伞偉伟傳传傷伤倀伥倫伦傖伧偽伪佇伫體体餘余傭佣僉佥俠侠侶侣僥侥偵侦側侧僑侨儈侩儕侪儂侬倆俩儉俭僂偻僱雇儔俦儐傧儼俨儲储儺傩儻傥儷俪兒儿兇凶兌兑黨党內内兩两興兴蘭兰關关養养嘆叹獸兽圇圆壚垆壟垄壩坝墾垦牆墙壇坛壞坏壋垱壯壮壺壶壼壸壽寿夠够夢梦夥伙夾夹奐奂奧奥奩奁奪夺奮奋妝妆婦妇媽妈嫵妩嫗妪姍姗姙妊姦奸嬪嫔嬙嫱孌娈孫孙學学寧宁寵宠審审寫写寬宽寰寰寶宝尋寻對对導导將将專专層层屬属岡冈峴岘島岛峽峡崗岗崍崃崳嵛嵐岚嶼屿嶺岭嶽岳巋岿巒峦巖岩帥帅師师帳帐簾帘幃帏幗帼幟帜幣币幫帮幀帧幾几庫库廂厢廄厩廈厦廳厅廡庑廠厂廢废廣广龐庞廬庐愛爱礙碍骯肮襖袄罷罢擺摆敗败頒颁闆板絆绊綁绑謗谤剝剥飽饱寶宝報报鮑鲍輩辈貝贝備备筆笔幣币畢毕閉闭邊边編编貶贬變变辯辩標标錶表彆别賓宾瀕濒繽缤餅饼並并駁驳鉑铂補补佈布財财採采綵彩參参殘残蠶蚕蒼苍艙舱測测層层詫诧摻掺攙搀禪禅纏缠產产鏟铲闡阐懺忏嘗尝償偿場场廠厂暢畅鈔钞車车徹彻塵尘陳陈襯衬稱称撐撑誠诚懲惩馳驰遲迟齒齿沖冲蟲虫籌筹齣出礎础處处觸触傳传瘡疮闖闯創创錘锤純纯詞词辭辞叢丛湊凑錯错噠哒達达帶带貸贷單单膽胆擔担誕诞彈弹當当蕩荡檔档導导盜盗燈灯鄧邓敵敌遞递點点電电釣钓調调頂顶訂订錠锭凍冻動动棟栋鬥斗獨独讀读賭赌鍍镀鍛锻斷断隊队對对噸吨頓顿奪夺墮堕惡恶兒儿爾尔發发罰罚閥阀琺珐煩烦範范販贩飯饭訪访紡纺飛飞費费紛纷墳坟奮奋風风楓枫瘋疯馮冯縫缝諷讽鳳凤膚肤婦妇複复賦赋復复蓋盖鈣钙幹干趕赶鋼钢崗岗綱纲閣阁個个給给宮宫鞏巩貢贡溝沟構构購购穀谷顧顾颳刮關关觀观館馆慣惯貫贯廣广歸归龜龟閨闺軌轨貴贵過过駭骇韓韩漢汉號号閡阂轟轰紅红後后護护華华畫画劃划懷怀壞坏歡欢環环還还換换黃黄揮挥輝辉匯汇賄贿穢秽繪绘葷荤渾浑獲获禍祸擊击機机積积雞鸡極极級级計计紀纪際际濟济繼继夾夹傢家價价駕驾殲歼監监堅坚間间揀拣鹼碱撿捡簡简見见劍剑踐践濺溅艦舰鑒鉴鍵键講讲獎奖醬酱膠胶澆浇驕骄嬌娇攪搅轎轿較较階阶潔洁結结節节驚惊經過經莖茎徑径競竞糾纠舊旧舉举據据劇剧懼惧絕绝軍军開开凱凯剴剀懇恳褲裤誇夸塊块礦矿虧亏潰溃擴扩闊阔臘腊蠟蜡來来蘭兰攔拦藍蓝覽览懶懒爛烂撈捞勞劳樂乐類类淚泪離离禮礼裡里麗丽勵励曆历歷历聯联蓮莲練练煉炼涼凉輛辆療疗鄰邻臨临靈灵鈴铃嶺岭劉刘龍龙樓楼錄录陸陆綠绿倫伦羅罗駱骆媽妈瑪玛買买麥麦賣卖滿满貓猫麼么沒没門门們们夢梦彌弥謎谜綿绵廟庙滅灭憫悯閩闽鳴鸣謀谋納纳難难撓挠惱恼腦脑鬧闹膩腻釀酿鳥鸟聶聂寧宁農农濃浓諾诺歐欧盤盘拋抛賠赔噴喷騙骗飄飘蘋苹憑凭頗颇樸朴僕仆鋪铺譜谱齊齐騎骑豈岂啟启氣气遷迁鉛铅謙谦潛潜淺浅槍枪牆墙橋桥竅窍翹翘輕轻傾倾請请慶庆窮穷區区確确讓让繞绕熱热認认榮荣軟软銳锐薩萨賽赛殺杀紗纱曬晒閃闪傷伤燒烧紹绍捨舍設设審审聲声勝胜聖圣濕湿詩诗時时實实識识勢势適适釋释壽寿獸兽輸输數数術术樹树雙双誰谁稅税說说絲丝飼饲鬆松蘇苏肅肃雖虽歲岁孫孙損损縮缩鎖锁態态壇坛談谈湯汤燙烫濤涛騰腾體体條条鐵铁聽听廳厅統统頭头圖图團团推薦駝驼駘骀窪洼萬万網网韋韦圍围維维偉伟偽伪衛卫溫温聞闻穩稳問问嗚呜無无吳吴務务誤误霧雾習习戲戏細细蝦虾嚇吓鮮鲜顯显險险縣县線线憲宪獻献鄉乡詳详響响項项蕭萧曉晓協协脅胁寫写謝谢興兴許许緒绪續续懸悬選选學学尋寻壓压鴉鸦鴨鸭煙烟鹽盐顏颜驗验陽阳楊扬養养藥药爺爷葉叶業业陰阴銀银應应擁拥優优憂忧郵邮猶犹遊游餘余魚鱼漁渔與与語语預预園园圓圆遠远願愿約约躍跃雲云運运雜杂災灾載载贊赞臟脏棗枣擇择澤泽賊贼贈赠紮扎軋轧閘闸詐诈齋斋氈毡盞盏張张賬账趙赵這这針针偵侦鎮镇掙挣鄭郑證证織织職职紙纸誌志質质腫肿種种眾众軸轴驟骤豬猪諸诸駐驻築筑轉转莊庄裝装壯壮狀状準准資资總总縱纵鑽钻嘴嘴組组';for(var i=0;i<s.length;i++){var c=s[i];var j=p.indexOf(c);r+=j>=0&&j%2===0?p[j+1]:c}return r}

// === 国内源富化封面+歌词 ===
async function enrichCover(artist,title,cand,cfg){var kw=artist+' '+title;var all=[];if(cfg.enable_netease&&cfg.netease_api_url){try{var nr=await fetchNetease(kw,cfg.netease_api_url);nr.forEach(function(r){r.score=scoreMatch(cand,r)});all=all.concat(nr)}catch(e){}await sleep(300)}if(cfg.enable_qqmusic&&cfg.qqmusic_api_url){try{var qr=await fetchQQ(kw,cfg.qqmusic_api_url);qr.forEach(function(r){r.score=scoreMatch(cand,r)});all=all.concat(qr)}catch(e){}await sleep(300)}if(cfg.enable_kugou&&cfg.kugou_api_url){try{var kr=await fetchKG(kw,cfg.kugou_api_url);kr.forEach(function(r){r.score=scoreMatch(cand,r)});all=all.concat(kr)}catch(e){}}var best=null,bs=-1;for(var i=0;i<all.length;i++){if(all[i].score>bs){bs=all[i].score;best=all[i]}}if(!best)return{};songloft.log.info('[enrich] '+best.source+' score='+bs.toFixed(2));var lyrics='';try{lyrics=await fetchLyrics(best,cand,kw)}catch(e){}return{cover_url:best.cover_url||'',lyrics:lyrics,source:best.source}}

// === 文本源 ===
async function fetchNetease(kw,url){try{var r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Referer':'https://music.163.com','User-Agent':'Mozilla/5.0'},body:'s='+encodeURIComponent(kw)+'&type=1&limit=3'});if(!r.ok)return[];var d=await r.json();var s=d.result&&d.result.songs?d.result.songs:[];return s.map(function(s){return{artist:(s.ar&&s.ar[0])?s.ar[0].name:'',title:s.name||'',album:s.al?s.al.name:'',cover_url:s.al&&s.al.picUrl?s.al.picUrl+'?param=500y500':'',source:'netease'}})}catch(e){return[]}}
async function fetchQQ(kw,url){try{var r=await fetch(url+'?w='+encodeURIComponent(kw)+'&format=json&n=3',{headers:{'Referer':'https://y.qq.com','User-Agent':'Mozilla/5.0'}});if(!r.ok)return[];var d=await r.json();var s=d.data&&d.data.song&&d.data.song.list?d.data.song.list:[];return s.map(function(s){return{artist:(s.singer&&s.singer[0])?s.singer[0].name:'',title:s.songname||'',album:s.albumname||'',cover_url:s.albummid?'https://y.gtimg.cn/music/photo_new/T002R500x500M000'+s.albummid+'.jpg':'',source:'qqmusic'}})}catch(e){return[]}}
async function fetchKG(kw,url){try{var r=await fetch(url+'?keyword='+encodeURIComponent(kw)+'&page=1&pagesize=3',{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)return[];var d=await r.json();var s=d.data&&d.data.lists?d.data.lists:[];return s.map(function(s){return{artist:s.SingerName||'',title:s.SongName||'',album:s.AlbumName||'',cover_url:s.AlbumImg||'',source:'kugou'}})}catch(e){return[]}}

// === 评分 ===
var SW={acoustid:1.5,netease:1.0,qqmusic:0.95,kugou:0.85};
function scoreMatch(c,r){var ac=(c.artist||'').trim().toLowerCase();var tc=(c.title||'').trim().toLowerCase();var ar=(r.artist||'').trim().toLowerCase();var tr=(r.title||'').trim().toLowerCase();if(!ar||!tr)return 0;var w=SW[r.source]||0.8;return(0.4*sim(ac,ar)+0.6*sim(tc,tr))*w}
function sim(a,b){if(!a&&!b)return 1;if(!a||!b)return 0;if(a===b)return 1;var t=a.length+b.length;if(!t)return 1;var m=0;function fb(s1,l1,h1,s2,l2,h2){var bl=0,b1=-1,b2=-1;for(var i=l1;i<h1;i++)for(var j=l2;j<h2;j++){var k=0;while(i+k<h1&&j+k<h2&&s1[i+k]===s2[j+k])k++;if(k>bl){bl=k;b1=i;b2=j}}if(bl>0){fb(s1,l1,b1,s2,l2,b2);m+=bl;fb(s1,b1+bl,h1,s2,b2+bl,h2)}}fb(a,0,a.length,b,0,b.length);return 2*m/t}

// === 标签写入 ===
async function writeTags(id,r){try{var t=await songloft.plugin.getToken();var h=await songloft.plugin.getHostUrl();var cd='';if(r.cover_url)try{var cr=await fetch(r.cover_url);if(cr.ok){var buf=await cr.arrayBuffer();var bytes=new Uint8Array(buf);var bin='';for(var i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);cd=btoa(bin)}}catch(e){}var resp=await fetch(h+'/api/v1/songs/'+id+'/tags',{method:'PUT',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({title:r.title,artist:r.artist,album:r.album||'',lyrics:r.lyrics||'',cover_data:cd})});if(!resp.ok)return'failed';var d=await resp.json();return d.file_write||'unknown'}catch(e){return'failed'}}
function sleep(ms){return new Promise(function(r){setTimeout(r,ms)})}

// === fpcalc 安装 ===
async function installFpcalc(){try{var u='https://github.com/acoustid/chromaprint/releases/download/v1.5.1/chromaprint-fpcalc-1.5.1-linux-x86_64.tar.gz';await songloft.command.download(u,'fpcalc.tar.gz');await songloft.command.exec('tar',['-xzf','fpcalc.tar.gz','--strip-components=1'],{timeout:30000});try{await songloft.command.deleteBin('fpcalc.tar.gz')}catch(e){}await songloft.command.exec('chmod',['+x','fpcalc'],{timeout:5000});return{success:true}}catch(e){return{success:false,error:String(e)}}}

// === 生命周期 ===
async function onInit(){songloft.log.info('[tag] 刮削插件已启动')}
async function onDeinit(){songloft.log.info('[tag] 刮削插件已卸载')}
async function onHTTPRequest(req){return router.handle(req)}
globalThis.onInit=onInit;globalThis.onDeinit=onDeinit;globalThis.onHTTPRequest=onHTTPRequest;
